### PR TITLE
delete extra > in num_exact regex

### LINKED ISSUE #411: January is not parsed correctly
```
> mdy("January131973")
[1] NA
```

Reported first at [stacoverflow](http://stackoverflow.com/questions/36971015/mdy-lubridate-unable-to-identify-january).

### PR DESCRIPTION
**Pull request by cderv**
fixes #411

Parsings seems to work with the code test I posted in the issue.
``` r
# With cderv/lubridate on branch locale_reg_bug
Sys.setlocale("LC_TIME", "French_France.1252")
#> [1] "French_France.1252"
vdate <- paste0(format(dmy("13/01/1973") + (0:11)*months(1), "%B"), "131973")
vdate
#>  [1] "janvier131973"   "février131973"   "mars131973"     
#>  [4] "avril131973"     "mai131973"       "juin131973"     
#>  [7] "juillet131973"   "août131973"      "septembre131973"
#> [10] "octobre131973"   "novembre131973"  "décembre131973"

mdy(vdate)
#>  [1] "1973-01-13" "1973-02-13" "1973-03-13" "1973-04-13" "1973-05-13"
#>  [6] "1973-06-13" "1973-07-13" "1973-08-13" "1973-09-13" "1973-10-13"
#> [11] "1973-11-13" "1973-12-13"
mdy(vdate[1])
#> [1] "1973-01-13"
mdy(vdate[2])
#> [1] "1973-02-13"
mdy(vdate[1:2])
#> [1] "1973-01-13" "1973-02-13"
mdy(vdate[c(1,1)])
#> [1] "1973-01-13" "1973-01-13"

Sys.setlocale("LC_TIME", "C")
#> [1] "C"

vdate <- paste0(format(dmy("13/01/1973") + (0:11)*months(1), "%B"), "131973")
vdate
#>  [1] "January131973"   "February131973"  "March131973"    
#>  [4] "April131973"     "May131973"       "June131973"     
#>  [7] "July131973"      "August131973"    "September131973"
#> [10] "October131973"   "November131973"  "December131973"

mdy(vdate)
#>  [1] "1973-01-13" "1973-02-13" "1973-03-13" "1973-04-13" "1973-05-13"
#>  [6] "1973-06-13" "1973-07-13" "1973-08-13" "1973-09-13" "1973-10-13"
#> [11] "1973-11-13" "1973-12-13"
mdy(vdate[1])
#> [1] "1973-01-13"
mdy(vdate[2])
#> [1] "1973-02-13"
mdy(vdate[1:2])
#> [1] "1973-01-13" "1973-02-13"
mdy(vdate[c(1,1)])
#> [1] "1973-01-13" "1973-01-13"
```

It is my first non typo-correction PR, so tell me if I must do something else.

- Should we had some tests ? 
- What other file should I modify in order for you to merge?

---
This change is [Reviewable](https://reviewable.io/reviews/hadley/lubridate/415)

### CODE REVIEW

**Comment by vspinu** [comment]
Yes. We will need some more tests for parsing. Could you please add them. Also add [Fix #411] in the commit message to automatically close the issue. Thanks for this.

**Comment by cderv** [comment]
Ok. I will try to write some tests in `test-parsers.R` for parsing with `mdy` and `b` or `B` format.

----

I could add [Fix #411 ] in the commit message but I understood that Github automatically close PR even if fixes #411 is added to the comment of the PR as I did. Capture of the Issue page :

2016-05-20 15_52_30-january is not parsed correctly issue 411 hadley_lubridate

see [Closing Issues via Pull Requests](https://github.com/blog/1506-closing-issues-via-pull-requests)

**Comment by cderv** [comment]
I added some tests for `b` and `B` formats. Actually, the issues in #411 was for a date format with no separators and with `January`. Tests I pushed cover this. Could had some more if we want to test parsing for all combination because I may have missed some.
As Travis checks passed, `mdy("January131973")`  works now.

Are we ok? 
Should I update NEWS file now with a commit containing [Fix #411] ?

**Comment by vspinu** [comment]
> Should I update NEWS file now with a commit containing [Fix #411] ? 

Ah. Sure. This is a major change. Thanks.

**Comment by cderv** [comment]
I add a line in NEWS using the correct format I believed. 
Don't know your contributor policy, so if my PR still miss something tell me. 
For example, don't know if I should modify something in DESCRIPTION.

If we are good, last things to do is merging! Glad I could find this bug and contribute!

**Comment by vspinu** [comment]
This is good. Thanks! :+1:

**Pull request merged**
