### PR TITLE
Add qday to getters and setters

### PR DESCRIPTION
**Pull request by jonboiser**
In reference to Issue #278, a `qday` can be implemented using the new `floor_date(x, "quarter")` functionality.

The "getter" `qday(x)` seems straightforward. The "setter" `qday(x)<-` seems to work, but its use of `day(x)<-` gives me pause, since the day setter has cool "magical" behavior that I don't fully understand.

### CODE REVIEW

**Comment by vspinu** [comment]
@jonboiser, any chance you can have a look at this once again? The test is failing due to missing documentation. There a bunch of other issues with `day` doc, so I will fix this myself once this is merged.

For now, could you please add a bunch of corner cases tests and squash all the commits in one? Thanks.

**Comment by jonboiser** [comment]
I missed the part about the docs, and added a couple of lines.  I added just a simple test for the accessor and handful of more intricate cases in the setters test file.

**Comment by vspinu** [comment]
Oups. I cannot automatically merge it. Would you mind rebasing. Must be a minor conflict.

**Comment by jonboiser** [comment]
It seems like there was a lot of activity in the repo since I started the PR. I rebased my fork on top of hadley/master

**Comment by vspinu** [comment]
So this one fixes #278, right? Could you please start the commit message with [Fix #278] so that that issue is automatically closed.

**Comment by vspinu** [comment]
>  start the commit message with [Fix #278] 

Never mind. I fixed that and merged your pull manually. Thanks.

**Pull request closed without merging**
