### PR TITLE
Small edits to docs.

### PR DESCRIPTION
**Pull request by Kevin-M-Smith**
This commit makes small changes to the documentation for lubridate. …
- Fix spacing typo.
- Add hours() link in docs for consistency
- Fix knitr close bracket in vignette

### CODE REVIEW

**Comment by vspinu** [comment]
Thanks. If it's not difficult for you, could you please squash commits 2,3 and 4th into one, as they relate to the same change?

**Comment by Kevin-M-Smith** [comment]
Hi @vspinu, thanks for your feedback. I attempted to squash everything. How's it look?

**Comment by vspinu** [comment]
Hi Kevin.

It looks good, but the comint message doesn't comply to standards. It should not contain "This comit makes ...", nor it should contain "to lubridate". These are obvious statements.

Messages should be imperative like, "Make small changes to ..." or simply "Small changes to documentation".  Here is a [good summary](https://github.com/erlang/otp/wiki/Writing-good-commit-messages) of standards.

**Comment by Kevin-M-Smith** [comment]
Hi @vspinu - I don't mean to burn through your time with these small edits. Thanks for helping me build better habits!

**Comment by vspinu** [comment]
> I don't mean to burn through your time with these small edits.

It's also your time ;). But it pays back in long run.

If I merge now I will merge  3 commits of yours - 2 identical commits which differ only in messages and one merge commit.  You can see this in the [network graph](https://github.com/Kevin-M-Smith/lubridate/network).

The way you should fix previous commits is not through new branches and merges as you seem to do, but rather through `git comit --amend` or `git reset HEAD^` and then `git commit`.  Then `git push --force`. 

Could you please do `git reset --hard bed50964` and then `git push --force` to get rid of the old branch?

**Comment by Kevin-M-Smith** [comment]
Thanks, I didn't realize the patch-2 branch was visible to this pull request. 

I've dropped it and reset the HEAD as requested.

**Comment by vspinu** [comment]
Thanks. :+1:

**Pull request merged**
